### ISSUE TITLE
Master Issue: Documentation

### ISSUE THREAD

**Issue by buck54321** [decred/dcrdex#1641]
Updates for the below items include both textual updates and more technical updates e.g. to message structures. Potential editors should feel free to update just the technical portions or to update just the text portions, as their aptitudes permit.

**If you're feeling motivated, please claim more than one at a time.**
## README
I'd like the README to be more marketing and less technical. 

**These sections should be made into wiki pages**

- [x] Client Quick Start Installation (@JoeGruffins #1715)
- [x] Client Configuration (@chappjc #1747)
- [x] Advanced Client Installation (@chappjc #1747)
- [x] Server Installation (@chappjc #1747)

## Specification
- [ ] README.mediawiki
- [ ] comms.mediawiki
- `connect` response
- [ ] fundamentals.mediawiki
- Ban score added to `config` response
- `maxFeeRate` and `swapSizeBase` updates fields added to `config` response
- [ ] admin.mediawiki
- [ ] accounts.mediawiki
- [ ] orders.mediawiki
- Order status reconciliation
- Negotiation acknowledgement changes
- [ ] api.mediawiki
- [ ] community.mediawiki  (#238)
- [ ] Need to describe trade suspension somewhere (#354)

## Wiki
[See the wiki homepage](https://github.com/decred/dcrdex/wiki) to see how to contribute here. 

- [ ] New Page: New asset integration
- [ ] New page: DEX account management. add/disable/discover/re-enable (@ukane-philemon #2468)
- [ ] DEX client backup and restoration. Can be part of clients page moved from README
- [ ] New page: Bonds, user score
- [ ] Update **Server Admin**
- Lot size / max fee rate arithmetic
- Market suspension / resumption
- [ ] **Testnet Testing** needs updating. It's tailored to RPC.
- [ ] New page: Bitcoin
- Wallet types
- Wallet configuration
- Fees and fee spikes
- [x] New page: Ethereum (@chappjc #2233)
- Wallet description
- Fees
- [ ] New page: Decred
- Mixed account setup
- [ ] New page: Tokens
- [ ] New pages maybe: Litecoin, Bitcoin Cash, Dogecoin, ZCash, Firo, Digibyte

Subsumes #707, #830, #354, #521, #238

**Please discuss. Will update based on feedback.**

**Comment by xaur** [comment]
Have you considered moving wiki contents into the main repo's [docs](https://github.com/decred/dcrdex/tree/master/docs) dir? I began doing that for my repos to make wiki contents subject to GitHub's pull request workflow. As a bonus, it consolidates all docs in one place.

**Comment by JoeGruffins** [comment]
I guess if noone else is chiming in, I'll take a swing at `Client Quick Start Installation` for the wiki.

**Comment by JoeGruffins** [comment]
@buck54321 srry, need clarification. `made into wiki pages` means moving to a `.mediawiki` file in `docs` maybe with a link there from the readme? Not moved to the dcrdex.wiki.

**Comment by buck54321** [comment]
I was thinking dcrdex wiki.

**Comment by buck54321** [comment]
I open to what @xaur is suggesting if it makes our life easier.

**Comment by chappjc** [comment]
The docs folder sounds fine to me too, but it would need to me .md files.  Rendering mediawiki locally isn't easy or widely available, but markdown is.

We can also use the wiki for fast drafting.  (just start hacking it up and we can collaboratively edit, then when we like it, check in a md version to the docs folder).  We just need to grant wiki perms to collaborators.

**Comment by JoeGruffins** [comment]
The three checked aren't moved to the wiki yet, just updated. Did you want to move them still?

**Comment by xaur** [comment]
Now that the wiki is just a subdirectory of the main repo, I wonder if there is a need to route [wiki contributors](https://github.com/decred/dcrdex/wiki) through GitHub Wiki features at all and have them to learn `git subtree`?

I think contributing steps can be simplifeid to "1. Fork dcrdex repo, 2. Edit files in `docs/wiki` dir, 3. Submit a PR. Your changes will eventually flow into our wiki pages". (Sorry if this issue is the wrong place to submit such feedback).

**Comment by buck54321** [comment]
I ran into this and thought it had a lot of good stuff in it.

https://jonatack.github.io/articles/how-to-review-pull-requests-in-bitcoin-core

**Comment by ukane-philemon** [comment]
> I ran into this and thought it had a lot of good stuff in it.

Cool, I enjoyed reading the article. Do we wish to have the `good stuffs` concentrated into an article specific for decred devs?

**Comment by xaur** [comment]
FYI we also have https://devdocs.decred.org/ for more general dev docs that apply to all repos.

**Comment by ukane-philemon** [comment]
> FYI we also have https://devdocs.decred.org/ for more general dev docs that apply to all repos.

Yeah, good call. We could improve our dev docs to include some more relevant information.

**Comment by JoeGruffins** [comment]
I'll attempt to update the comms mediawiki.

What purpose does the `README.mediawiki` in the root dir serve?

**Comment by JoeGruffins** [comment]
I'll work on  fundamentals.mediawiki, admin.mediawiki, accounts.mediawiki, orders.mediawiki, and I guess the README.mediawiki in spec

**Comment by dev-warrior777** [comment]
> "New pages maybe: Litecoin, Bitcoin Cash, Dogecoin, ZCash"

Let me know what would be appropriate for Firo and I can write that based on the general pattern

**Comment by chappjc** [comment]
> > "New pages maybe: Litecoin, Bitcoin Cash, Dogecoin, ZCash"
> 
> Let me know what would be appropriate for Firo and I can write that based on the general pattern

Generic pages for (1) full node bitcoind-like wallets, and (2) Electrum wallets would be the place to start.  There are few differences between the coins, but any can be called out in sub-sections of those 2 pages.

**Comment by ukane-philemon** [comment]
> Small concern here is to test that GitHub wiki can handle subdirectories.

I dunno, can check it out but found this: https://github.com/orgs/community/discussions/23914

**Comment by ukane-philemon** [comment]
@buck54321, please can you update this issue when you're a bit free?

**Comment by xaur** [comment]
Following the [link](https://github.com/orgs/community/discussions/23914) from @ukane-philemon I did some experiments with my [test wiki](https://github.com/xaur/dcrfun/wiki).

What I found:

- **Moving pages to subdirs does not break the wiki**
  - If you [clone this url](https://github.com/xaur/dcrfun.wiki.git) you will see the pages are now indeed in `users`, `admins`, and `developers` subdirectories.
  - [Autogenerated sidebbar](https://github.com/xaur/dcrfun/wiki) still works.
  - Moves are also shown in the [history diff](https://github.com/xaur/dcrfun/wiki/_compare/fd6cb0e30e00ff865747e5e84b00fe23857e3282...8181781d1fb738623e099c2f39c9c88faf8a6f5d).

- **Directories cannot be seen or manipulated with web UI**
  - [Autogenerated sidebbar](https://github.com/xaur/dcrfun/wiki) shows all pages in a flat list ignoring any subdirectories.
  - The [`wiki/_pages`](https://github.com/xaur/dcrfun/wiki/_pages) special page shows all pages in a flat list.

- **Editing pages in subdirectories locally - works**
  - Changes are properly shown in [root History](https://github.com/xaur/dcrfun/wiki/_history) - [example diff](https://github.com/xaur/dcrfun/wiki/_compare/1302bf4105fc821b640c4a3ead3aea65329731d6...4858159dec537e7ff69d9de0c9f8c1980720d940)
  - Changes are properly shown in the [History for that page](https://github.com/xaur/dcrfun/wiki/Client-Installation-and-Configuration/_history) - [example diff](https://github.com/xaur/dcrfun/wiki/Client-Installation-and-Configuration/_compare/8181781d1fb738623e099c2f39c9c88faf8a6f5d...4858159dec537e7ff69d9de0c9f8c1980720d940)
  - Changes to .md are propagated to the rendered pages [like here](https://github.com/xaur/dcrfun/wiki/Client-Installation-and-Configuration) (I made "standalone DEX client" bold).

- **Editing pages in subdirs with web UI - works**
  - Even though GitHub does not show its subdir path anywhere in the process, the page gets [updated](https://github.com/xaur/dcrfun/wiki/Client-Installation-and-Configuration) and [stays in the subdir](https://github.com/xaur/dcrfun/wiki/Client-Installation-and-Configuration/_compare/4858159dec537e7ff69d9de0c9f8c1980720d940...b06a8e930d6d0f392cbfbfc5618fed580241e22e) where it was.
  - DCRDEX wiki does not need web UI editing now but it was nice to see it works. It means that subdirectory support is not that bad even if there is no web UI to see or manage it.

- **Custom sidebar works**
  - The effect is the autogenerated **Pages** sidebar section becomes collapsed by default and our `_Sidebar.md` contents are shown instead.
  - Local links work with one caveat - we have to remove all subdirectories and extension to match GitHub's rendered paths

Overall this seems to work. I don't expect pages to be created or renamed too often so a manual sidebar does not seem like too much effort. The only issue I couldn't fix is the smaller font of sidebar items.

You can check how it looks in [my test wiki](https://github.com/xaur/dcrfun/wiki) or on the screenshots linked below:

- [Autogenerated Pages sidebar](https://github.com/decred/dcrdex/assets/24484727/336e2384-bfa1-4cca-9216-4aec5d6681b8)
- [Custom sidebar with normal links](https://github.com/decred/dcrdex/assets/24484727/0666cee4-52f9-4b5a-bbb8-e2878cf0e054)
- [Custom sidebar with H3 headings abused for links (too much padding)](https://github.com/decred/dcrdex/assets/24484727/cb331513-8b3e-415b-a14a-339e7dcf9cc5)
- [Custom sidebar with bold links](https://github.com/decred/dcrdex/assets/24484727/533a4ce2-6e65-4792-a194-5bbe044e42db)

Final version I settled on:

![](https://github.com/decred/dcrdex/assets/24484727/533a4ce2-6e65-4792-a194-5bbe044e42db)

**Comment by ukane-philemon** [comment]
Thanks @xaur for the detailed investigation. I think the final version looks good enough.

**Comment by xaur** [comment]
Another downside of my [custom sidebar idea](https://github.com/decred/dcrdex/issues/1641#issuecomment-1676400979) is that the auto-generated table of contents on the right becomes hidden by default (and users may not easily discover it).

I found another way to make an entry point page to help end users quickly discover docs intended for them. It requires very small changes: just list the guides for each audience in the [Home page](https://github.com/decred/dcrdex/wiki) ([example](https://raw.githubusercontent.com/wiki/xaur/dcrfun/_Sidebar.md)). If that is something wanted I can make a PR.

**Comment by ukane-philemon** [comment]
@buck54321, I'm picking up ` [] Testnet Testing needs updating. It's tailored to RPC`

**Comment by buck54321** [comment]
I've failed to keep up with this master issue. I'll try again when I have the time.
